version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  flask-app:
    build: ./path/to/your/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres

networks:
  my_network:

volumes:
  db_data:

